spring:
  rabbitmq:
    listener:
      simple:
        auto-startup: false
  data:
    mongodb:
      database: study_mate_test
server:
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE