spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_ID}
    password: ${POSTGRES_PW}
    url: jdbc:postgresql://${POSTGRES_ADDRESS}:5432/study_mate
    hikari:
      connectionTimeout: 10000
      maximumPoolSize: 10
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    open-in-view: false
  rabbitmq:
    host: ${POSTGRES_ADDRESS}
    port: 5672
    username: ${POSTGRES_ID}
    password: ${POSTGRES_PW}
  data:
    mongodb:
      authentication-database: admin
      username: ${POSTGRES_ID}
      password: ${POSTGRES_PW}
      host: localhost
      port: 27017
server:
  port: 8000
secret-key: ${JWT_SECRET}
aws:
  client-id: ${AWS_CLIENT_ID}
  cert-path: ${AWS_CERT_PATH}
  key-path: ${AWS_KEY_PATH}
  cert-auth-path: ${AWS_CERT_AUTH_PATH}
  endpoint: ${AWS_ENDPOINT}
