spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_ID}
    password: ${POSTGRES_PW}
    url: jdbc:postgresql://${POSTGRES_ADDRESS}:5432/study_mate
    hikari:
      connectionTimeout: 10000
      maximumPoolSize: 10
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    open-in-view: false
  rabbitmq:
    host: ${POSTGRES_ADDRESS}
    port: 5672
    username: ${POSTGRES_ID}
    password: ${POSTGRES_PW}
    listener:
      simple:
        auto-startup: true
  data:
    mongodb:
      authentication-database: admin
      username: ${POSTGRES_ID}
      password: ${POSTGRES_PW}
      database: study_mate
      host: localhost
      port: 27017
  security:
    user:
      name: ${POSTGRES_ID}
      password: ${POSTGRES_PW}
  devtools:
    add-properties: false
    livereload:
      enabled: false
server:
  port: 8000
  error:
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
logging:
  level:
    root: info
secret-key: ${JWT_SECRET}