spring:
  rabbitmq:
    listener:
      simple:
        auto-startup: true
  data:
    mongodb:
      database: study_mate
  security:
    user:
      name: ${POSTGRES_ID}
      password: ${POSTGRES_PW}
  devtools:
    add-properties: false
    livereload:
      enabled: false
server:
  error:
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
logging:
  level:
    root: info