spring:
  jpa:
    properties:
      hibernate.format_sql: true
  rabbitmq:
    listener:
      simple:
        auto-startup: true
  data:
    mongodb:
      database: study_mate

server:
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE