version: "3.9"
services:
  nginx:
    image: nginx:latest
    depends_on:
      - api
      - websocket
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./cert:/etc/nginx/cert
    environment:
      - TZ=Asia/Seoul
  api:
    image: eutrocee/study-mate-api
    build: api
    depends_on:
      - postgresql
      - mongodb
    ports:
      - "8000:8000"
    environment:
      - AWS_CERT_AUTH_PATH
      - AWS_CERT_PATH
      - AWS_CLIENT_ID
      - AWS_ENDPOINT
      - AWS_KEY_PATH
      - JWT_SECRET
      - MONGODB_ADDRESS=mongodb
      - POSTGRES_ADDRESS=postgresql
      - POSTGRES_ID
      - POSTGRES_PW
      - TZ=Asia/Seoul
    volumes:
      - ./api_server_credential:/usr/src/app/api_server_credential
  postgresql:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_ID}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=study_mate
      - TZ=Asia/Seoul
  mongodb:
    image: mongo:focal
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=0000
      - MONGO_INITDB_DATABASE=study_mate
      - TZ=Asia/Seoul
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  websocket:
    image: eutrocee/study-mate-websocket
    build: websocket
    ports:
      - "8080:8080"
    environment:
      - WS_AWS_CERT_AUTH_PATH
      - WS_AWS_CERT_PATH
      - WS_AWS_CLIENT_ID
      - AWS_ENDPOINT
      - WS_AWS_KEY_PATH
      - JWT_SECRET
      - TZ=Asia/Seoul
    volumes:
      - ./websocket_server_credential:/usr/src/app/websocket_server_credential