version: "3.9"
services:
  websocket:
    build: .
    ports:
      - "8080:8080"
    environment:
      - WS_AWS_CERT_AUTH_PATH
      - WS_AWS_CERT_PATH
      - WS_AWS_CLIENT_ID
      - AWS_ENDPOINT
      - WS_AWS_KEY_PATH
      - JWT_SECRET